---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piphp
  labels:
    app: piphp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: piphp
  template:
    metadata:
      labels:
        app: piphp
    spec:
      containers:
        - name: stack
          image: ceil-router.dev:5001/helmuthva/piphp
          ports:
            - containerPort: 80
